[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "showcase"
  name = "Projects"
  url = "showcase"
  weight = 2

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 3

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 4
[[main]]
  identifier = "notes"
  name = "Notes"
  url = "https://g-savitha.github.io/categories/"
  weight = 5
[[main]]
  identifier = "contact"
  name = "Contact"
  url = "contact"
  weight = 6