[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase"
  weight = 2

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 3

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 4
[[main]]
  identifier = "newsletter"
  name = "Newsletter"
  url = "https://www.getrevue.co/profile/gsavitha"
  weight = 5
