[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 2

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 3
[[main]]
  identifier = "notes"
  name = "Notes"
  url = "https://g-savitha.github.io/categories/"
  weight = 4
