baseURL = "https://g-savitha.github.io/"
languageCode = "en-us"
title = "Savitha's Notes"

theme = "0x32"              # theme name
disableKinds = []           # disable stuffs
enableGitInfo = true        # valuable git information
enableEmoji = true          # enables emoji support in content files

[markup]
[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 1

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = false
tabWidth = 2
style = "dracula"


[permalinks]
pages = "/:filename"
posts = "/:year/:title/"
notes = "/notes/:filename"
